# settings.yaml

# Camera settings
camera_id: 2
camera_width: 1920
camera_height: 1080

# Cube detection color ranges (RGB)
cube_detection:
  blue:
    rgb_ranges:
      - lower: [100, 0, 0]
        upper: [255, 170, 55]
  brown:
    rgb_ranges:
      - lower: [0, 0, 170]
        upper: [85, 255, 255]

thresholds:
  cube_area_min: 350
  cube_width_min: 10
  cube_height_min: 10

orderpoints:
  - [710, 355]
  - [665, 731]
  - [1278, 707]
  - [1178, 343]

# Chessboard settings
chessboard_size: [8, 8]
warped_size: [800, 800]

# New parameters for black line detection
line_deviation_threshold: 20
initialization_frames: 30

# Points for chessboard processing
chessboard_points:
  - - 772
    - 367
  - - 1204
    - 359
  - - 1284
    - 718
  - - 741
    - 733
obstacle_detection_points:
  - - 767
    - 302
  - - 1197
    - 289
  - - 1321
    - 831
  - - 718
    - 849
