from chess_logic.opening_line import OpeningLine

openings = [
    OpeningLine(
        "London System introduction",
        [
            "The move is Pawn d4. The pawn is controlling center squares.",
            "The move is Pawn d5.",
            "The move is Bishop f4. The first rule is after d4 and d5 you bring your bishop to the f4 square.",
            "The move is Knight f6.",
            "The move is Pawn e3. The second rule is to create a solid pawn chain and finish later with pawn c3.",
            "The move is Pawn c5.",
            "The move is Pawn c3. You should finish the pawn chain with pawn c3.",
            "The move is Knight c6.",
            "The move is Knight d2. You are trying to develop your knight.",
            "The move is Pawn e6.",
            "The move is Knight f3. You are trying to develop your final knight and completing your basic setup.",
            "The move is Pawn c5.",
            "The move is Knight d2. If your enemy plays c5, always play Knight bd2 because of the move Queen b6. That move would give black a chance to equalize.",
            "The move is Knight c6.",
            "The move is knight gf3. The third rule is to develop your minor pieces to it's destined squares.",
            "The move is Bishop d6.",
            "The move is Bishop g3. This is a key move to remember if black plays Bishop d6, because you don't wanna mess up your pawn structure. You could try to capture that bishop on d6, but it just releases the tension and that's already an achievment for black. If he captures your bishop, your rook wil have an semi open H-file.",
            "The move is short castles.",
            "The move is bishop d3. All minor pieces are developed.",
            "The move is queen e7. Black wants to prepare pawn e5.",
            "The move is Knight e5. You want to prevent black from playing pawn e5. If you're playing the london system, never allow black to push pawn to e5 to make his light-squared bishop become alive.",
            "The move is Knight d7",
            "The move is Pawn f4. This is the last key move you have to remember. Wer're not just supporting our knight on e5, but we also have created a structure that is called the Stonewall attack but with a bishop on g3. In the normal stonewall that bishop stays on his home on c3.",
        ],
        [
            "d2d4",
            "d7d5",
            "c1f4",
            "g8f6",
            "e2e3",
            "c7c5",
            "c2c3",
            "b8c6",
            "b1d2",
            "e7e6",
            "g1f3",
            "c7c5",
            "b1d2",
            "b8c6",
            "g1f3",
            "f8d6",
            "f4g3",
            "e8g8",
            "f1d3",
            "d8e7",
            "f3e5",
            "f6d7",
            "f2f4",
        ],
    )
]
